name : 'discord-release'
description: 'Send release to discord message'
author: 'Mex Delgado'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  owner:
    description: 'Repo owner'
    required: true
  repo:
    description: 'Repo name'
    required: true
  webhook:
    description: 'discord webhook'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
