name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: First GitHub Custom Action
        id: 'discordRelease'
        uses: ./
        with:
          name-of-user: 'Mex'

      - name: Output of the TimeStamp
        run: echo "The time was ${{steps.discordRelease.outputs.time}}"
