name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: First GitHub Custom Action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
