name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: First GitHub Custom Action
        id: 'discordRelease'
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          owner: 'tresdoce'
          repo: 'tresdoce-nestjs-toolkit'
          tag: '@tresdoce-nestjs-toolkit/typeorm@0.1.0-beta.0'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Output of the TimeStamp
        run: echo "The time was ${{steps.discordRelease.outputs.time}}"
